### PR TITLE
PT-10066 | Updating the dependency to make it work with latest sonarqube

### PR DESCRIPTION
**Pull request by bhargavkeshav**

### CODE REVIEW

**Comment by bhargavkeshav** [comment]
Running tests against the changes and creation of jar.

```
bhargav.n@MacBookPro-BhargavN sonar-auth-google % mvn clean install          
[INFO] Scanning for projects...
[INFO] 
[INFO] ------< org.sonarqube.auth.google:sonar-auth-googleoauth-plugin >-------
[INFO] Building Google Authentication for SonarQube 1.0.0
[INFO]   from pom.xml
[INFO] ----------------------------[ sonar-plugin ]----------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2: https://issues.sonatype.org/browse/MVNCENTRAL-244
[INFO] 
[INFO] --- clean:3.2.0:clean (default-clean) @ sonar-auth-googleoauth-plugin ---
[INFO] Deleting /Users/bhargav.n/acquia/repos/sonar-auth-google/target
[INFO] 
[INFO] --- sonar-packaging:1.15:check (default-check) @ sonar-auth-googleoauth-plugin ---
[INFO] 
[INFO] --- jacoco:0.8.11:prepare-agent (agent-for-ut) @ sonar-auth-googleoauth-plugin ---
[INFO] argLine set to -javaagent:/Users/bhargav.n/.m2/repository/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/Users/bhargav.n/acquia/repos/sonar-auth-google/target/jacoco.exec,append=true
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ sonar-auth-googleoauth-plugin ---
[INFO] Copying 2 resources from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.11.0:compile (default-compile) @ sonar-auth-googleoauth-plugin ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 7 source files with javac [debug target 1.8] to target/classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/GoogleIdentityProvider.java: /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/GoogleIdentityProvider.java uses or overrides a deprecated API.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/GoogleIdentityProvider.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/AuthGooglePlugin.java: /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/AuthGooglePlugin.java uses unchecked or unsafe operations.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/main/java/org/sonarqube/auth/googleoauth/AuthGooglePlugin.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- resources:3.3.1:testResources (default-testResources) @ sonar-auth-googleoauth-plugin ---
[INFO] skip non existing resourceDirectory /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/resources
[INFO] 
[INFO] --- compiler:3.11.0:testCompile (default-testCompile) @ sonar-auth-googleoauth-plugin ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO] Compiling 7 source files with javac [debug target 1.8] to target/test-classes
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/IntegrationTest.java: /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/IntegrationTest.java uses or overrides a deprecated API.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/IntegrationTest.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/AuthGooglePluginTest.java: /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/AuthGooglePluginTest.java uses unchecked or unsafe operations.
[INFO] /Users/bhargav.n/acquia/repos/sonar-auth-google/src/test/java/org/sonarqube/auth/googleoauth/AuthGooglePluginTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- surefire:3.2.2:test (default-test) @ sonar-auth-googleoauth-plugin ---
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.sonarqube.auth.googleoauth.GoogleSettingsTest
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.238 s -- in org.sonarqube.auth.googleoauth.GoogleSettingsTest
[INFO] Running org.sonarqube.auth.googleoauth.GoogleIdentityProviderTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.638 s -- in org.sonarqube.auth.googleoauth.GoogleIdentityProviderTest
[INFO] Running org.sonarqube.auth.googleoauth.GoogleScribeApiTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s -- in org.sonarqube.auth.googleoauth.GoogleScribeApiTest
[INFO] Running org.sonarqube.auth.googleoauth.UserIdentityFactoryTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.071 s -- in org.sonarqube.auth.googleoauth.UserIdentityFactoryTest
[INFO] Running org.sonarqube.auth.googleoauth.AuthGooglePluginTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s -- in org.sonarqube.auth.googleoauth.AuthGooglePluginTest
[INFO] Running org.sonarqube.auth.googleoauth.IntegrationTest
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56435] starting to accept connections
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56435] received request: POST /oauth2/v3/token HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56435] received request: GET /oauth2/v1/userinfo?access_token=e72e16c7e42f292c6912e7710c838347ae178b4a HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56435] done accepting connections: Socket closed
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56438] starting to accept connections
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56438] received request: POST /oauth2/v3/token HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56438] received request: GET /oauth2/v1/userinfo?access_token=e72e16c7e42f292c6912e7710c838347ae178b4a HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56438] done accepting connections: Socket closed
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56441] starting to accept connections
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56441] received request: POST /oauth2/v3/token HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56441] received request: GET /oauth2/v1/userinfo?access_token=e72e16c7e42f292c6912e7710c838347ae178b4a HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56441] done accepting connections: Socket closed
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56444] starting to accept connections
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56444] done accepting connections: Socket closed
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56445] starting to accept connections
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56445] received request: POST /oauth2/v3/token HTTP/1.1 and responded: HTTP/1.1 200 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[56445] received request: GET /oauth2/v1/userinfo?access_token=e72e16c7e42f292c6912e7710c838347ae178b4a HTTP/1.1 and responded: HTTP/1.1 500 OK
Jan 10, 2024 1:17:20 PM com.squareup.okhttp.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56445] done accepting connections: Socket closed
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.230 s -- in org.sonarqube.auth.googleoauth.IntegrationTest
[INFO] Running org.sonarqube.auth.googleoauth.GsonUserTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s -- in org.sonarqube.auth.googleoauth.GsonUserTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- sonar-packaging:1.15:sonar-plugin (default-sonar-plugin) @ sonar-auth-googleoauth-plugin ---
[INFO] -------------------------------------------------------
[INFO] Plugin definition in update center
[INFO]     Key: authgoogleoauth
[INFO]     Name: Google Authentication for SonarQube
[INFO]     Description: A plugin for SonarQube which provides the ability to authenticate using Google's OAuth2 service.
    The plugin can also be configured via the Google Developer's Console to limit the authentication domain. Compatible
    with SonarQube version 5.6 and higher.
[INFO]     Version: 1.0.0
[INFO]     Entry-point Class: org.sonarqube.auth.googleoauth.AuthGooglePlugin
[INFO]     Required Plugins: 
[INFO]     Use Child-first ClassLoader: false
[INFO]     Base Plugin: 
[INFO]     Homepage URL: https://github.com/InfoSec812/sonar-auth-google
[INFO]     Minimal SonarQube Version: 5.4
[INFO]     Licensing: GNU LGPL 3
[INFO]     Organization: Zanclus Consulting
[INFO]     Organization URL: http://www.zanclus.com/
[INFO]     Terms and Conditions: 
[INFO]     Issue Tracker URL: https://github.com/InfoSec812/sonar-auth-google/issues
[INFO]     Build date: 2024-01-10T13:17:20+0530
[INFO]     Sources URL: https://github.com/InfoSec812/sonar-auth-google
[INFO]     Developers: Joseph "Deven" Phillips (InfoSec812),Julien Lancelot
[WARNING] While downloading org.apache.commons:commons-io:1.3.2
  This artifact has been relocated to commons-io:commons-io:1.3.2.
  https://issues.sonatype.org/browse/MVNCENTRAL-244


[INFO]     Dependencies: META-INF/lib/commons-lang-2.6.jar META-INF/lib/sonar-plugin-api-9.11.0.290.jar META-INF/lib/scribejava-core-2.1.0.jar META-INF/lib/commons-codec-1.15.jar META-INF/lib/sonar-plugin-api-impl-9.7.1.62043.jar META-INF/lib/gson-2.8.5.jar META-INF/lib/sonar-analyzer-commons-2.1.0.1111.jar META-INF/lib/scribejava-apis-2.1.0.jar META-INF/lib/commons-csv-1.9.0.jar
[INFO] -------------------------------------------------------
[INFO] Building jar: /Users/bhargav.n/acquia/repos/sonar-auth-google/target/sonar-auth-googleoauth-plugin-1.0.0.jar
[INFO]  already added, skipping
[INFO] 
[INFO] --- license:1.9:download-licenses (download-licenses) @ sonar-auth-googleoauth-plugin ---
[WARNING] Unable to retrieve license for dependency: javax.servlet:javax.servlet-api
[WARNING] https://glassfish.dev.java.net/nonav/public/CDDL+GPL.html
[WARNING] No subject alternative DNS name matching glassfish.dev.java.net found.
[INFO] 
[INFO] --- jacoco:0.8.11:prepare-agent-integration (agent-for-it) @ sonar-auth-googleoauth-plugin ---
[INFO] argLine set to -javaagent:/Users/bhargav.n/.m2/repository/org/jacoco/org.jacoco.agent/0.8.11/org.jacoco.agent-0.8.11-runtime.jar=destfile=/Users/bhargav.n/acquia/repos/sonar-auth-google/target/jacoco.exec,append=true
[INFO] 
[INFO] --- jacoco:0.8.11:report (jacoco-site) @ sonar-auth-googleoauth-plugin ---
[INFO] Loading execution data file /Users/bhargav.n/acquia/repos/sonar-auth-google/target/jacoco.exec
[INFO] Analyzed bundle 'Google Authentication for SonarQube' with 6 classes
[INFO] 
[INFO] --- install:3.1.1:install (default-install) @ sonar-auth-googleoauth-plugin ---
[INFO] Installing /Users/bhargav.n/acquia/repos/sonar-auth-google/pom.xml to /Users/bhargav.n/.m2/repository/org/sonarqube/auth/google/sonar-auth-googleoauth-plugin/1.0.0/sonar-auth-googleoauth-plugin-1.0.0.pom
[INFO] Installing /Users/bhargav.n/acquia/repos/sonar-auth-google/target/sonar-auth-googleoauth-plugin-1.0.0.jar to /Users/bhargav.n/.m2/repository/org/sonarqube/auth/google/sonar-auth-googleoauth-plugin/1.0.0/sonar-auth-googleoauth-plugin-1.0.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.699 s
[INFO] Finished at: 2024-01-10T13:17:40+05:30
[INFO] ------------------------------------------------------------------------

```

**Review by rohitss912 — APPROVED** [review]
LGTM!

Plugin installation is happening successfully on 10.3 SQ & OAuth is working as expected.
Screenshot 2024-01-11 at 12 39 04 PM

**Review by ABSK-AB — APPROVED** [review]
looks good to me

**Review by sumitgupta21 — APPROVED** [review]
Looks good. 
Sonarqube is tested with new plugin jar and oAuth login working fine : 
image

**Pull request merged**
